## Import Packages

In [11]:
import pandas as pd
import numpy as np

In [12]:
np.set_printoptions(suppress= True, linewidth=100, precision=2)

In [13]:
## Ada Missing Values
raw_data = np.genfromtxt("./loan-data.csv", delimiter=";")
raw_data

array([[        nan,         nan,         nan, ...,         nan,         nan,         nan],
       [48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [14]:
## Hapus Header(nama kolom) dan Space diantaranya
raw_data = np.genfromtxt("./loan-data.csv", delimiter=";",skip_header=1, autostrip=True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Check Data Yang mising

In [15]:
raw_data.shape

(10000, 14)

In [16]:
## Cek Jumlah Data Yang Missing Totalnya Ada 88.005 dari 140.000 
np.isnan(raw_data).sum()

88005

## Bikin Dua Variabel Buat Ngisi Missing Data

In [17]:
temporary_fill = np.nanmax(raw_data) + 1 ## Buat Ngisi Data Yang Kosong
temporary_mean = np.nanmean(raw_data, axis=0) ## Mean Buat Semua Kolom

C:\Users\ganoa\AppData\Local\Temp\ipykernel_9656\2184448722.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis=0) ## Mean Buat Semua Kolom


In [18]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [19]:
temporary_stats = np.array([np.nanmin(raw_data, axis= 0), temporary_mean, np.nanmax(raw_data, axis= 0)])

C:\Users\ganoa\AppData\Local\Temp\ipykernel_9656\1113361446.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data, axis= 0), temporary_mean, np.nanmax(raw_data, axis= 0)])


In [20]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting The Dataset

In [21]:
## Cara Biar Tau Yang Mana Text Data + Squeeze Biar Datanya Datar
collum_string = np.argwhere(np.isnan(temporary_mean)).squeeze()
collum_string

## Diperoleh Kolom 1,3,5,8,9,10,11,12 Isinya adalah text/string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [22]:
## Cara Biar Tau Yang Mana Numeric Data
collum_numeric = np.argwhere(np.isnan(temporary_mean)== False).squeeze()
collum_numeric

## Diperoleh Kolom 0,2,4,6,7,13 Isinya adalah numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

## Import Ulang Data

In [23]:
## Dataset-nya menjadi 2 String dan Numeric - Yg ini string
loan_data_string = np.genfromtxt("./loan-data.csv", 
                   delimiter=";",
                   skip_header=1, 
                   autostrip=True,
                   usecols= collum_string, 
                   dtype=np.string_)
loan_data_string

array([[b'May-15', b'Current', b'36 months', ..., b'Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', b'CA'],
       [b'', b'Current', b'36 months', ..., b'Source Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', b'NY'],
       [b'Sep-15', b'Current', b'36 months', ..., b'Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', b'PA'],
       ...,
       [b'Jun-15', b'Current', b'36 months', ..., b'Source Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', b'CA'],
       [b'Apr-15', b'Current', b'36 months', ..., b'Source Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', b'OH'],
       [b'Dec-15', b'Current', b'36 months', ..., b'',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', b'IL']],
      dtype='|S69')

In [24]:
## Dataset-nya menjadi 2 String dan Numeric - Yg ini numeric
loan_data_numeric = np.genfromtxt("./loan-data.csv", 
                    delimiter=";",skip_header=1, 
                    autostrip=True,
                    usecols= collum_numeric,
                    filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

## Nama Dari Kolom

In [25]:
raw_data = np.genfromtxt("./loan-data.csv", delimiter=";",skip_header=1, autostrip=True)

In [26]:
## Yang dibuang Usecols, skip_header diganti Jadi Skip_footer=dataset pertama atau(raw_data)

kolom_data = np.genfromtxt("./loan-data.csv", 
                   delimiter=";",
                   skip_footer=raw_data.shape[0], 
                   autostrip=True, 
                   dtype=np.string_)
kolom_data

array([b'id', b'issue_d', b'loan_amnt', b'loan_status', b'funded_amnt', b'term', b'int_rate',
       b'installment', b'grade', b'sub_grade', b'verification_status', b'url', b'addr_state',
       b'total_pymnt'], dtype='|S19')

In [27]:
kolom_data_string = kolom_data[collum_string]

In [28]:
kolom_data_numeric = kolom_data[collum_numeric]

In [29]:
kolom_data_string

array([b'issue_d', b'loan_status', b'term', b'grade', b'sub_grade', b'verification_status', b'url',
       b'addr_state'], dtype='|S19')

In [30]:
kolom_data_numeric

array([b'id', b'loan_amnt', b'funded_amnt', b'int_rate', b'installment', b'total_pymnt'],
      dtype='|S19')

## Preprocessing Dataset
### Manupulating String Collum

In [31]:
kolom_data_string ## Disini kita ubah kolom 0 "issue_d" = "Issue_date" | Biar lebih bagus aja

array([b'issue_d', b'loan_status', b'term', b'grade', b'sub_grade', b'verification_status', b'url',
       b'addr_state'], dtype='|S19')

In [34]:
kolom_data_string[0] = "issue_date" ## Data berhasil di update
kolom_data_string

array([b'issue_date', b'loan_status', b'term', b'grade', b'sub_grade', b'verification_status',
       b'url', b'addr_state'], dtype='|S19')

In [32]:
loan_data_string 

array([[b'May-15', b'Current', b'36 months', ..., b'Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', b'CA'],
       [b'', b'Current', b'36 months', ..., b'Source Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', b'NY'],
       [b'Sep-15', b'Current', b'36 months', ..., b'Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', b'PA'],
       ...,
       [b'Jun-15', b'Current', b'36 months', ..., b'Source Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', b'CA'],
       [b'Apr-15', b'Current', b'36 months', ..., b'Source Verified',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', b'OH'],
       [b'Dec-15', b'Current', b'36 months', ..., b'',
        b'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', b'IL']],
      dtype='|S69')

## Issues Date

In [35]:
loan_data_string[:,0] ## Munculin kolom pertama saja

array([b'May-15', b'', b'Sep-15', ..., b'Jun-15', b'Apr-15', b'Dec-15'], dtype='|S69')

In [37]:
np.unique(loan_data_string[:,0]) ## np.unique buat cari data yang unik 
                                 ## Hanya ada 1 data yang berbeda yaitu baris pertama = ""/ Kosong

array([b'', b'Apr-15', b'Aug-15', b'Dec-15', b'Feb-15', b'Jan-15', b'Jul-15', b'Jun-15', b'Mar-15',
       b'May-15', b'Nov-15', b'Oct-15', b'Sep-15'], dtype='|S69')

In [39]:
## Kita mau ubah / buang angka 15 yang mewakili tahun biar datanya hanya bulan saja
loan_data_string[:,0] =np.chararray.strip(loan_data_string[:,0],"-15") ## Jangan lupa kolom mana yang mau kita ubah

In [41]:
np.unique(loan_data_string[:,0]) ## Yup data sdh diupdate

array([b'', b'Apr', b'Aug', b'Dec', b'Feb', b'Jan', b'Jul', b'Jun', b'Mar', b'May', b'Nov', b'Oct',
       b'Sep'], dtype='|S69')

In [47]:
## Kita mau ubah bulannya menjadi angka
mount = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [53]:
## Buat For i loop
for i in range(13):
        loan_data_string[:,0] = np.where(loan_data_string[:,0] == mount[i],i,loan_data_string[:,0])

In [54]:
np.unique(loan_data_string[:,0])

array([b'', b'Apr', b'Aug', b'Dec', b'Feb', b'Jan', b'Jul', b'Jun', b'Mar', b'May', b'Nov', b'Oct',
       b'Sep'], dtype='|S69')