In [1]:
import pandas as pd
import numpy as np

In [2]:
lending_co_data_numeric = np.loadtxt("./Lending-company-Numeric.csv", delimiter= ',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
lending_co_data_numeric.shape

(1043, 6)

In [4]:
type(lending_co_data_numeric)

numpy.ndarray

In [5]:
np.isnan(lending_co_data_numeric) ## Untuk ngecek apakah ada missing data (false = tidak ada yg mising, true = ada yang mising)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [6]:
np.isnan(lending_co_data_numeric).sum() ## Ditambah sum di akhir kalau hasilnya = 0 berati tidak ada missing 
                                        ## jika hasilnya = 1 maka ada mising 

0

In [7]:
lending_co_data_nan = np.loadtxt("./Lending-company-Numeric-NAN.csv", delimiter=';') ## Hasilnya error karena ada data yang missing

ValueError: could not convert string to float: ''

## Cara import buat data yang missing

In [ ]:
lending_co_data_nan = np.genfromtxt("./Lending-company-Numeric-NAN.csv", delimiter=';')
lending_co_data_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.isnan(lending_co_data_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
np.isnan(lending_co_data_nan).sum() ## Biar tahu ada berapa data yang mising Totalnya da 260 data yang mising

260

In [ ]:
lending_co_data_nan.shape

(1043, 6)

In [ ]:
temporary_fill = np.nanmax (lending_co_data_nan).round(2) + 1

In [ ]:
## Kasih nilai sementara ke data yang missing (kita isi dengan nilai tertinggi dari data)
lending_co_data_nan = np.genfromtxt("./Lending-company-Numeric-NAN.csv", delimiter=';', filling_values=temporary_fill)

In [ ]:
np.isnan(lending_co_data_nan) ## sekarang data yang mising sdh terisi dengan nilai tertinggi dari data

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [ ]:
np.isnan(lending_co_data_nan).sum() ## Hasilnya 0 tidak ada data yang missng lagi

0

## Subtituting missing values in ndarray

In [ ]:
### Disini saya akan menggunakan nilai rata2 untuk mengisi data yang kosong 
### Agar tidak terlalu berpengaruh pada analisis

lending_co_data_nan = np.genfromtxt('./Lending-company-Numeric-NAN.csv', delimiter=";")
lending_co_data_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.nanmean(lending_co_data_nan)

4758.213571190397

In [ ]:
lending_co_data_nan = np.genfromtxt('./Lending-company-Numeric-NAN.csv', delimiter=";",filling_values= 4758)

In [ ]:
lending_co_data_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [ ]:
np.average(lending_co_data_nan) ### Oke Cool

4758.204697986577

In [ ]:
df_nan = np.genfromtxt('./Lending-company-Numeric-NAN.csv', delimiter=';', filling_values=0)

In [ ]:
np.average(df_nan)

4560.5249280920425

In [ ]:
df_nan_temporary = np.genfromtxt("./Lending-company-Numeric-NAN.csv", delimiter=";",filling_values=0)

In [ ]:
np.average(df_nan_temporary[:,0])

2176.893576222435

### Solusi terbaik adalah menggunakan average masing2 dari tiap kolom waktu yang digunakan tetapi hasil yang diperoleh lebih relevan

In [ ]:
np.average(df_nan_temporary[:,1])

43.983700862895496

In [ ]:
df_nan_temporary[:,0]

array([2000., 2000., 1000., ...,    0., 1000., 2000.])

In [ ]:
df_nan_temporary[:,0]= np.where(df_nan_temporary[:,0],)

### Kita coba pakai data yang sederhana XIXI

In [ ]:
df = np.array([[1,2,3,0,5],[6,7,8,9,10],[11,12,13,14,32],[23,32,45,12,67]])
df

array([[ 1.,  2.,  3., nan,  5.],
       [ 6.,  7.,  8.,  9., nan],
       [11., nan, 13., 14., 32.],
       [nan, 32., 45., 12., 67.]])

In [ ]:
temporary_fill_df = np.nanmean(df).round(2) + 1
temporary_fill_df

17.69

In [ ]:
test_df = df
test_df

array([[ 1.,  2.,  3., nan,  5.],
       [ 6.,  7.,  8.,  9., nan],
       [11., nan, 13., 14., 32.],
       [nan, 32., 45., 12., 67.]])

In [ ]:
test_df = np.nan()

array([[ 1.,  2.,  3., nan,  5.],
       [ 6.,  7.,  8.,  9., nan],
       [11., nan, 13., 14., 32.],
       [nan, 32., 45., 12., 67.]])

In [ ]:
np.savetxt('df.csv',df,fmt='%d',delimiter=',')

ValueError: cannot convert float NaN to integer