In [1]:
import pandas as pd
import numpy as np

## 1. Ndarray

### originate from the numpy package

### Spesial datatype dari python dimana kita bisa store banyak numeric values berurutan

In [2]:
array_a = np.array([1,43,56]) ## Ini 1 dimensi array
array_a

array([ 1, 43, 56])

In [3]:
array_b = np.array([[12,32,45],[12,34,56]]) ## 2 dimensi Array
array_b

array([[12, 32, 45],
       [12, 34, 56]])

In [4]:
type(array_a)

numpy.ndarray

In [5]:
array_b.shape

(2, 3)

## Array vs List

In [6]:
list = [[1,2,3,4],[32,34,53,53]]
list

[[1, 2, 3, 4], [32, 34, 53, 53]]

In [7]:
len(list)

2

In [8]:
array = np.array([[12,34,23],[123,432,12]])
array

array([[ 12,  34,  23],
       [123, 432,  12]])

In [9]:
type(list)

list

In [10]:
type(array)

numpy.ndarray

In [11]:
print(list) ## Outputnya dalam bentuk 1 baris aja

[[1, 2, 3, 4], [32, 34, 53, 53]]


In [12]:
print(array) ## outputnya dalam bentuk 2 dimensi atau seperti tabel yanga da baris dan kolom

[[ 12  34  23]
 [123 432  12]]


### List dan array perbedaan utamanya dari syntax dan outputnya tetapi list juga bisa dimasukan ke dalam array 

## String vs object vs Number

In [13]:
lending = np.genfromtxt('./Lending-company.csv', delimiter=",")

In [15]:
lending

array([nan, nan, nan, ..., nan, nan, nan])