In [1]:
import pandas as pd
import numpy as np

## Learn how to work with numpy array
## Focus on the diference types of slicing
## discuse and when we use the squeeze fungtions

In [2]:
## Slicing
metrix_a = np.array ([[12,23,45],[12,34,54]])

In [3]:
metrix_a

array([[12, 23, 45],
       [12, 34, 54]])

### Pada Artikel Kali ini akan dijelaskan mengenai "Belajar Numpy Python : Array Indexing dan Slicing". Array indexing adalah cara dalam mengakses elemen array, Anda dapat mengakses elemen pada array dengan Nomor Index, Contoh : variabel_i[index ke berapa] ATAU variabel_a[elemen ke berapa][index ke berapa]. 
Sedangkan Slicing adalah Memotong elemen Array menggunakan index yang diberikan. Contoh Slice : [mulai:selesai] atau [mulai:] atau [:selesai] . 

In [4]:
metrix_a[:]

array([[12, 23, 45],
       [12, 34, 54]])

In [5]:
metrix_a[:1]

array([[12, 23, 45]])

In [6]:
metrix_a[1:2]

array([[12, 34, 54]])