In [1]:
import pandas as pd
import numpy as np

In [2]:
dataframe = pd.read_csv("./simple_csv.csv")

In [3]:
dataframe.to_numpy()

array([[0.28092541, 0.91036848, 0.69298188],
       [0.71988236, 0.21002407, 0.7612759 ],
       [0.23575208, 0.0597963 , 0.1546666 ],
       [0.60336627, 0.48561397, 0.01334502],
       [0.03998475, 0.23635865, 0.81183165],
       [0.01547756, 0.54364108, 0.11271945],
       [0.19253954, 0.40987429, 0.87508246],
       [0.3809206 , 0.04546771, 0.5158594 ],
       [0.59247137, 0.78642122, 0.04724929],
       [0.07211205, 0.69569385, 0.4095732 ],
       [0.89807238, 0.07095587, 0.20902018],
       [0.72203752, 0.21198538, 0.32416377],
       [0.51351671, 0.09154813, 0.66427856],
       [0.43672924, 0.04032155, 0.54816704],
       [0.86403942, 0.96355627, 0.10639842],
       [0.72476104, 0.41042245, 0.58758877],
       [0.19892576, 0.24520742, 0.76735595],
       [0.74849989, 0.01926363, 0.04667836],
       [0.92063933, 0.21261146, 0.52046319],
       [0.45202421, 0.12366004, 0.84745113],
       [0.54297722, 0.2658523 , 0.41092586],
       [0.35526598, 0.86061556, 0.58943068],
       [0.

In [6]:
dataframe_array = dataframe.to_numpy()

In [8]:
dataframe_array

array([[0.28092541, 0.91036848, 0.69298188],
       [0.71988236, 0.21002407, 0.7612759 ],
       [0.23575208, 0.0597963 , 0.1546666 ],
       [0.60336627, 0.48561397, 0.01334502],
       [0.03998475, 0.23635865, 0.81183165],
       [0.01547756, 0.54364108, 0.11271945],
       [0.19253954, 0.40987429, 0.87508246],
       [0.3809206 , 0.04546771, 0.5158594 ],
       [0.59247137, 0.78642122, 0.04724929],
       [0.07211205, 0.69569385, 0.4095732 ],
       [0.89807238, 0.07095587, 0.20902018],
       [0.72203752, 0.21198538, 0.32416377],
       [0.51351671, 0.09154813, 0.66427856],
       [0.43672924, 0.04032155, 0.54816704],
       [0.86403942, 0.96355627, 0.10639842],
       [0.72476104, 0.41042245, 0.58758877],
       [0.19892576, 0.24520742, 0.76735595],
       [0.74849989, 0.01926363, 0.04667836],
       [0.92063933, 0.21261146, 0.52046319],
       [0.45202421, 0.12366004, 0.84745113],
       [0.54297722, 0.2658523 , 0.41092586],
       [0.35526598, 0.86061556, 0.58943068],
       [0.

In [11]:
dataframe_array[[2,4,6]] ## Kalau spesifik value | sama kayak yg di pandas iloc

array([[0.23575208, 0.0597963 , 0.1546666 ],
       [0.03998475, 0.23635865, 0.81183165],
       [0.19253954, 0.40987429, 0.87508246]])

In [15]:
dataframe_array[2][2] ## Kita mau cari row 2 dari kolom 2 ** Ingat Python perhitungan dimulai dari 0

0.154666599

## Assigning Values in NumPy

In [17]:
array_np = np.array([[12,34,56],[34,56,78]])

In [18]:
array_np

array([[12, 34, 56],
       [34, 56, 78]])

In [21]:
array_np [0,2]=5 ## Ngubah isi array disini mau ngubah 34 jadi 5
array_np

array([[12, 34,  5],
       [34, 56, 78]])

In [24]:
array_np [1] = 12 ## Kita ngubah baris ke dua jadi 12 semua jadi hati2 saat mengubah harus teliti
array_np

array([[12, 34,  5],
       [12, 12, 12]])

In [27]:
array_np[:,0] = 25 ## Ngubah kolom 0 jadi 25 semua
array_np

array([[25, 34,  5],
       [25, 12, 12]])

In [29]:
list_a = np.array([3,4,5])

In [30]:
list_a

array([3, 4, 5])

In [35]:
array_np[1] = list_a ## Kita mau ngubah isi array yang baris 1 dengan isi dari list_a
array_np

array([[25, 34,  5],
       [ 3,  4,  5]])

## Elementwise Properties of Arrays

In [36]:
array_np

array([[25, 34,  5],
       [ 3,  4,  5]])

In [37]:
array_np + 5 ## Disini kita bisa nambah 5 ke semua isi dari array

array([[30, 39, 10],
       [ 8,  9, 10]])

In [38]:
array_np ** 2 ## Bisa juga matematic operations yang lainnya misalnya pangkat

array([[ 625, 1156,   25],
       [   9,   16,   25]], dtype=int32)

In [43]:
array_np /2

array([[12.5, 17. ,  2.5],
       [ 1.5,  2. ,  2.5]])

In [42]:
array_np 

array([[25, 34,  5],
       [ 3,  4,  5]])

In [45]:
array_np * 5 /2 ## Bisa lebih dari satu dicoba aja yang lainnya

array([[62.5, 85. , 12.5],
       [ 7.5, 10. , 12.5]])

In [46]:
array_np_b = array_np * 5 /2

In [47]:
array_np + array_np_b ## Bisa juga nambah dari 2 array yang berbeda

array([[ 87.5, 119. ,  17.5],
       [ 10.5,  14. ,  17.5]])

## Kalau mau nambah dari 1 atau dua baris array ke array yang banyak tinggal di kasih tanda [] buat spesifikan yang mau di ubah

In [50]:
array_a = np.array([[1,2,3],[3,3,4]])
array_a

array([[1, 2, 3],
       [3, 3, 4]])

In [52]:
array_b = np.array([12,34,56])
array_b

array([12, 34, 56])

In [53]:
array_b + array_a [0] ## Ini contohnya 

array([13, 36, 59])

In [54]:
array_ab = array_b + array_a [0]
array_ab 

array([13, 36, 59])

In [56]:
array_a[0]=array_ab ## Ini kalau mau masukin yg sdh di tambah td ke array_a

In [58]:
array_a ## Syaratnya panjang/ jumlah harus sama antar dua array

array([[13, 36, 59],
       [ 3,  3,  4]])

In [59]:
array_a + array_ab ## bisa juga semua isi dari array 

array([[ 26,  72, 118],
       [ 16,  39,  63]])

## Types of data supported by numpy

## Characteristics of NumPy Functions Part 1

## universal fungtions
 ### bekerja dengan ndarray pada elemen demi elemen
 ### an extensions of the elementwise operations
 ### operasi matematika, fungsi trigonometri, fungsi perbandingan
 ### broadcasting, type casting computing over a given axis

In [ ]:
## universal fungtions
 ### bekerja dengan ndarray pada elemen demi elemen
 ### an extensions of the elementwise operations
 ### operasi matematika, fungsi trigonometri, fungsi perbandingan
 ### broadcasting, type casting computing over a given axis

### Broadcasting

In [64]:
array_x = np.array([1,2,3,4])
array_x

array([1, 2, 3, 4])

In [61]:
array_y = np.array([[1],[2]])
array_y

array([[1],
       [2]])

In [62]:
array_z = np.array ([[1,2,3,4],[5,6,7,8]])
array_z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Pengertian Broadcasting

#### Broadcasting adalah salah satu konsep terpenting dalam NumPy. Setelah sebelumnya kita belajar tentang struktur data, indexing (view), indexing (copy), dan vektorisasi, tibalah saatnya kita mempelajari konsep kelima: Broadcasting. Secara sederhana, konsep broadcasting sama dengan istilah broadcasting di bidang lain. Misalnya pada aplikasi pesan melalui Whatsapp, broadcasting pada aplikasi tersebut berarti mengirim pesan pada semua akun yang ada di daftar kontak kita. Pada NumPy array, broadcasting juga berlaku demikan. Nilai (misal: array 1x2) yang dikalikan pada array vektor (4x1), maka setiap elemen vektor tersebut akan dikalikan dengan nilai tadi (array 1x2).



In [66]:
np.add(array_x,array_z) ## Halisnya menjadi array_x ditambahkan ke array_z meskipun strukturnya berbeda karena di broadcasting

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

### Type Fungtions

In [67]:
np.add(array_x,array_z, dtype=float) ## Ngubang type datanya | Jadi float dsini kasusnya

array([[ 2.,  4.,  6.,  8.],
       [ 6.,  8., 10., 12.]])

### Running over an axis

In [69]:
array_z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
np.mean(array_z, axis= 0) ## axiy = 0 artinya menemukan mean atau nilai tengah dari setiap dataframe/array

array([3., 4., 5., 6.])

In [70]:
np.mean(array_z, axis=1) ## axis = 1 menemukan nilai mean dari setiap baris

array([2.5, 6.5])

In [ ]:
S