In [24]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [8]:
pd_empty = np.empty(shape=(2,5))
pd_empty

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
pr_zeroes = np.zeros(shape=(2,5)) ## Bedanya dari yg pd.empty(), yang zeroes hasilnya pasti 0 tidak ada nan
pr_zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
pd_ones = np.ones(shape=(2,5), dtype=np.int8)
pd_ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [32]:


pd_full = np.full(shape=(2,3),fill_value=12)
pd_full

array([[12, 12, 12],
       [12, 12, 12]])